services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: music
            MYSQL_ROOT_PASSWORD: csc1csc2
            MYSQL_USER: csc
            MYSQL_PASSWORD: csc1csc2
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.2
        links:
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: csc
            MYSQL_PASSWORD: csc1csc2
            PMA_HOST: db
        volumes:
            - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
            - ./phpmyadmin-overrides/column_row.twig:/var/www/html/templates/table/insert/column_row.twig
            - ./phpmyadmin-overrides/Template.php:/var/www/html/libraries/classes/Template.php
volumes:
    persistent:
